trigger:
  branches:
    include:
      - main  # Change this to your branch name if needed

pool:
  vmImage: 'ubuntu-latest'

variables:
  CI: true


steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - task: Cache@2
    inputs:
      key: 'npm | "$(Agent.OS)" | package-lock.json'
      restoreKeys: |
        npm | "$(Agent.OS)"
      path: $(Pipeline.Workspace)/.npm
    displayName: 'Cache npm packages'

  - script: |
      npm ci
      npx playwright install --with-deps
    displayName: 'Install dependencies and Playwright'

  - script: |
      echo "Running tests against: $SFDC_BASE_URL"
      npx playwright test --project=sfui
    displayName: 'Run Playwright Tests for Project "wip"'
    env:
      SFDC_PASSWORD: $(SFDC_PASSWORD)
      SFDC_TOKEN: $(SFDC_TOKEN)
      SFDC_CLIENT_ID: $(SFDC_CLIENT_ID)
      SFDC_CLIENT_SECRET: $(SFDC_CLIENT_SECRET)


  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/test-results/**/*.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)'
