trigger:
  branches:
    include:
      - main  # Change this to your branch name if needed

pool:
  vmImage: 'ubuntu-latest'

variables:
  CI: true
  SFDC_BASE_URL: $(SFDC_BASE_URL)
  SFDC_USERNAME: $(SFDC_USERNAME)
  SFDC_PASSWORD: $(SFDC_PASSWORD)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm ci
      npx playwright install --with-deps
    displayName: 'Install dependencies and Playwright'

  - script: |
      echo "Running tests against: $SFDC_BASE_URL"
      npx playwright test --project=wip
    displayName: 'Run Playwright Tests for Project "wip"'
    env:
      SFDC_BASE_URL: $(SFDC_BASE_URL)
      SFDC_USERNAME: $(SFDC_USERNAME)
      SFDC_PASSWORD: $(SFDC_PASSWORD)

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/test-results/**/*.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)'
